#!/usr/bin/env node
/**
 * THE LOOP — a generated shot closed into a seamless loop, for free.
 *
 *   node scripts/loop.mjs <name> <clip>        close .footage/<name>/<clip>.master.mp4 (or <clip>.mp4) into <clip>.loop.mp4
 *   node scripts/loop.mjs --file <video.mp4>   any video; the output lands beside it as <stem>.loop.mp4
 *   flags: --out <file>          also copy the loop and its preview there (a site's public folder, a Downloads folder)
 *          --size WxH            output size, cover-fitted (default: the record size in studio.config; 1920x1080 when unset)
 *          --fps N               output frame rate (default: the source's)
 *          --pingpong            play the clip forward then backward (frames [0,cut) then (cut-2 .. 1)): a loop with NO seam by
 *                                construction, for motion that oscillates anyway (breathing, swaying grass, a flickering flame);
 *                                wrong for motion with a direction (walking, drifting clouds), which would visibly reverse
 *          --blend auto|off|N    cross-fade the head over the tail for N frames; auto (default) blends only when the seam is not clean
 *          --even auto|off|on    re-pick frames at an even pace so a model that braked into its end frame does not make the loop
 *                                breathe; auto (default) does it when either end runs under 60% of the clip's pace
 *          --tail N              frames at the end searched for the duplicate of frame 0 (default 12)
 *          --dup-ssim X          the SSIM a tail frame needs to count as that duplicate (default 0.95)
 *          --crf N               x264 quality (default 18)
 *          --cycles N            a preview that plays the loop N times, stream-copied (default 3; 0 = none)
 *
 * A loop is GENERATED by handing the model the same still as first and last frame
 * (`refs.images: [still, still]` on an image-to-video endpoint), so the shot comes
 * back to where it began. This closes it (the math is in footage/loop-math.mjs):
 * the tail frame that duplicates frame 0 is found and the clip is cut there; the
 * seam (last frame → first frame) is measured against the clip's own frame-to-frame
 * motion; a seam that steps further than its neighbours do is blended; the result
 * is cover-fitted to the exact frame size and written with a report
 * (<out>.loop.json), a seam contact sheet (<out>.loop.seam.jpg: the last frame
 * beside the first, as the loop point plays) and an N-cycle preview
 * (<out>-x3.mp4) to watch the join without a player's own gap.
 *
 * Nothing here spends, and the master is never touched.
 */

import { createHash } from 'node:crypto'
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'
import { arg, config, ffmpeg, ffmpegPath, footageDir, has, r2, ROOT } from './lib.mjs'
import { blendFrames, blendPlan, evenFrames, motionProfile, pickCut, seamVerdict } from './footage/loop-math.mjs'

const usage = () => {
  console.error('Usage: node scripts/loop.mjs <name> <clip> | --file <video.mp4>   [--out f] [--size WxH] [--fps N] [--blend auto|off|N] [--tail N] [--dup-ssim X] [--crf N] [--cycles N]')
  process.exit(1)
}

// ── what to close ───────────────────────────────────────────────────────────
let input
let label
let outBase
if (has('file')) {
  input = resolve(arg('file'))
  if (!existsSync(input)) usage()
  label = basename(input).replace(/\.[a-z0-9]+$/i, '')
  outBase = join(dirname(input), label)
} else {
  const [name, clip] = process.argv.slice(2).filter((a, i, all) => !a.startsWith('--') && !(i > 0 && all[i - 1].startsWith('--')))
  if (!name || !clip) usage()
  const dir = footageDir(name)
  input = [join(dir, `${clip}.master.mp4`), join(dir, `${clip}.mp4`)].find((f) => existsSync(f))
  if (!input) {
    console.error(`\n  no ${clip}.master.mp4 or ${clip}.mp4 in ${dir} — render the shot first (npm run footage -- ${name} --go)\n`)
    process.exit(1)
  }
  label = `${name}/${clip}`
  outBase = join(dir, clip)
}
const OUT = `${outBase}.loop.mp4`
const REPORT = `${outBase}.loop.json`
const SHEET = `${outBase}.loop.seam.jpg`
const cycles = Math.max(0, Math.round(Number(arg('cycles', '3'))))
const PREVIEW = cycles > 1 ? `${outBase}.loop-x${cycles}.mp4` : null

const FF = await ffmpegPath()
const cfg = config()
const rel = (p) => String(p).replace(`${ROOT}/`, '')
const tmp = join(ROOT, '.cache', 'loop', label.replace(/[^A-Za-z0-9_.-]/g, '_'))
rmSync(tmp, { recursive: true, force: true })
mkdirSync(tmp, { recursive: true })

// ── read the source ─────────────────────────────────────────────────────────
function probe(file) {
  const err = ffmpeg(FF, ['-hide_banner', '-i', file, '-map', '0:v:0', '-an', '-f', 'null', '-'], `probe ${basename(file)}`)
  const stream = /Video:.*?(\d{2,5})x(\d{2,5}).*?([\d.]+) fps/.exec(err)
  let frames = null
  for (const m of err.matchAll(/frame=\s*(\d+)/g)) frames = +m[1]
  let last = null
  for (const m of err.matchAll(/time=(\d+):(\d+):([\d.]+)/g)) last = m
  return {
    width: stream ? +stream[1] : null,
    height: stream ? +stream[2] : null,
    fps: stream ? +stream[3] : null,
    frames,
    seconds: last ? r2(+last[1] * 3600 + +last[2] * 60 + +last[3]) : null,
  }
}
const src = probe(input)
if (!src.frames || !src.fps) {
  console.error(`\n  cannot read ${rel(input)} (frames ${src.frames}, fps ${src.fps})\n`)
  process.exit(1)
}
const fps = Number(arg('fps')) > 0 ? Number(arg('fps')) : src.fps
const sizeArg = /^(\d+)x(\d+)$/.exec(arg('size') ?? '')
const W = sizeArg ? +sizeArg[1] : cfg.record?.width ?? 1920
const H = sizeArg ? +sizeArg[2] : cfg.record?.height ?? Math.round((W * 9) / 16)
const fit = `scale=${W}:${H}:force_original_aspect_ratio=increase:flags=lanczos,crop=${W}:${H},setsar=1,format=yuv420p`

console.log(`\n  loop ${label}: ${src.width}x${src.height} · ${src.fps} fps · ${src.frames} frames · ${src.seconds}s → ${W}x${H} · ${fps} fps`)

// ── the motion profile: how far each frame steps from the one before ────────
function motionDiffs(file) {
  const out = join(tmp, 'motion.txt')
  ffmpeg(FF, ['-hide_banner', '-i', file, '-vf', `tblend=all_mode=difference,signalstats,metadata=print:key=lavfi.signalstats.YAVG:file=${out}`, '-an', '-f', 'null', '-'], 'motion profile')
  const vals = [...readFileSync(out, 'utf8').matchAll(/lavfi\.signalstats\.YAVG=([\d.]+)/g)].map((m) => +m[1])
  // tblend's first output blends frame 0 with itself: no step there.
  return vals.length >= src.frames ? vals.slice(1) : vals
}
const diffs = motionDiffs(input)
const motion = motionProfile(diffs)
console.log(`  motion: a frame steps ${motion.median.toFixed(2)} (median luma change) · ease in ×${motion.easeIn.toFixed(2)} · ease out ×${motion.easeOut.toFixed(2)}${motion.easeOut < 0.5 ? '  ⚠ the model brakes into the end frame' : ''}`)

// ── the duplicate: which tail frame is frame 0 again ────────────────────────
const T = Math.min(Math.max(2, Math.round(Number(arg('tail', '12')))), src.frames - 2)
const first = join(tmp, 'first.png')
ffmpeg(FF, ['-hide_banner', '-y', '-i', input, '-vf', "select='eq(n,0)'", '-frames:v', '1', first], 'first frame')
ffmpeg(FF, ['-hide_banner', '-y', '-i', input, '-vf', `select='gte(n,${src.frames - T})'`, '-fps_mode', 'passthrough', join(tmp, 'tail-%03d.png')], 'tail frames')
const tailFrame = (index) => join(tmp, `tail-${String(index - (src.frames - T) + 1).padStart(3, '0')}.png`)

function ssim(a, b) {
  const err = ffmpeg(FF, ['-hide_banner', '-i', a, '-i', b, '-lavfi', '[0]format=yuv444p[a];[1]format=yuv444p[b];[a][b]ssim', '-f', 'null', '-'], 'ssim')
  const m = /All:([\d.]+)/.exec(err)
  return m ? +m[1] : null
}
/** The luma step between two frames, on the same scale as the motion profile. */
function step(a, b) {
  const out = join(tmp, 'step.txt')
  ffmpeg(FF, ['-hide_banner', '-i', a, '-i', b, '-lavfi', `[0]format=yuv444p[a];[1]format=yuv444p[b];[a][b]blend=all_mode=difference,signalstats,metadata=print:key=lavfi.signalstats.YAVG:file=${out}`, '-f', 'null', '-'], 'seam step')
  const m = /lavfi\.signalstats\.YAVG=([\d.]+)/.exec(readFileSync(out, 'utf8'))
  return m ? +m[1] : null
}

const tail = []
for (let index = src.frames - T; index < src.frames; index++) if (existsSync(tailFrame(index))) tail.push({ index, ssim: ssim(tailFrame(index), first) })
const cut = pickCut(src.frames, tail, { dupSsim: Number(arg('dup-ssim', '0.95')) })
console.log(`  tail vs frame 0 (ssim): ${tail.map((t) => `${t.index}:${t.ssim?.toFixed(3)}`).join(' ')}`)
console.log(cut.duplicate != null ? `  frame ${cut.duplicate} is frame 0 again (ssim ${cut.ssim.toFixed(3)}) → keep ${cut.cut} frames, drop ${cut.dropped}` : `  no tail frame duplicates frame 0 (best ssim ${cut.ssim?.toFixed(3) ?? 'n/a'}) → keep all ${cut.cut} frames`)

// ── the seam: the step from the loop's last frame back to its first ─────────
const lastKept = tailFrame(cut.cut - 1)
const seamStep = existsSync(lastKept) ? step(lastKept, first) : null
const seam = seamStep == null ? { seamless: false, ratio: null } : seamVerdict(seamStep, motion.median)
console.log(`  seam: last → first steps ${seamStep?.toFixed(2) ?? '?'} = ×${seam.ratio == null ? '?' : seam.ratio.toFixed(2)} of a normal step → ${seam.seamless ? 'clean, a plain cut' : 'a visible step'}`)

// ── even out the pace, or not ───────────────────────────────────────────────
// A model that brakes into its end frame (and starts slowly out of it) makes the
// loop breathe once per cycle. Re-picking frames at equal increments of motion
// plays the slow stretches through at the clip's own median pace; the seam is
// then one median step by construction, so no blend is needed on top.
const evenArg = String(arg('even', 'auto'))
const braked = Math.min(motion.easeIn, motion.easeOut) < 0.6
let even = null
if (evenArg === 'on' || (evenArg === 'auto' && braked)) {
  const keep = evenFrames(diffs, cut.cut, seamStep ?? motion.median, motion.median)
  if (keep.length < cut.cut) even = { kept: keep.length, dropped: cut.cut - keep.length, targetStep: r2(motion.median), frames: keep }
  console.log(even ? `  even: ${even.kept} of ${cut.cut} frames re-picked at one median step each (${even.dropped} dropped where the model braked)` : '  even: the pace is already even, nothing re-picked')
} else if (braked) console.log('  ⚠ the loop will breathe once per cycle — --even on re-picks frames at an even pace')

// ── ping-pong: forward then backward, no seam to hide ───────────────────────
const PINGPONG = has('pingpong')
if (PINGPONG) console.log(`  ping-pong: frames [0,${cut.cut}) forward then ${cut.cut - 2} backward → ${cut.cut + cut.cut - 2} frames, the motion reverses at both ends`)

// ── blend or not ────────────────────────────────────────────────────────────
const blendArg = String(arg('blend', 'auto'))
let blend = null
if (blendArg !== 'off' && !even && !PINGPONG) {
  const n = /^\d+$/.test(blendArg) ? Number(blendArg) : !seam.seamless ? blendFrames(src.fps) : 0
  if (n > 0) {
    try {
      blend = blendPlan(cut.cut, n, src.fps)
      console.log(`  blend: the first ${n} frames fade in over the last ${n} → ${blend.outFrames} frames, the loop point moves inside the fade`)
    } catch (e) {
      console.log(`  ⚠ ${e.message} — plain cut instead`)
    }
  }
}

// ── build ───────────────────────────────────────────────────────────────────
const enc = ['-r', String(fps), '-c:v', 'libx264', '-preset', 'slow', '-crf', String(Number(arg('crf', '18'))), '-profile:v', 'high', '-pix_fmt', 'yuv420p', '-movflags', '+faststart', '-an', OUT]
const pts = `setpts=N/(${src.fps}*TB)`
if (PINGPONG) {
  const keepSel = even ? even.frames.map((i) => `eq(n,${i})`).join('+') : `lt(n,${cut.cut})`
  const backSel = even ? even.frames.slice(1, -1).map((i) => `eq(n,${i})`).join('+') : `between(n,1,${cut.cut - 2})`
  const fc = [`[0:v]select='${keepSel}',${pts},${fit}[f]`, `[0:v]select='${backSel}',reverse,${pts},${fit}[r]`, `[f][r]concat=n=2:v=1:a=0,${pts},format=yuv420p[v]`].join(';')
  ffmpeg(FF, ['-hide_banner', '-y', '-i', input, '-filter_complex', fc, '-map', '[v]', ...enc], 'encode ping-pong loop')
} else if (blend) {
  const fc = [
    `[0:v]select='between(n,${blend.bodyFrom},${blend.bodyTo - 1})',${pts},${fit}[body]`,
    `[0:v]select='lt(n,${blend.headTo})',${pts},${fit}[head]`,
    `[body][head]xfade=transition=fade:duration=${blend.durationSec}:offset=${blend.offsetSec},format=yuv420p[v]`,
  ].join(';')
  ffmpeg(FF, ['-hide_banner', '-y', '-i', input, '-filter_complex', fc, '-map', '[v]', ...enc], 'encode blended loop')
} else {
  const select = even ? `select='${even.frames.map((i) => `eq(n,${i})`).join('+')}'` : `select='lt(n,${cut.cut})'`
  ffmpeg(FF, ['-hide_banner', '-y', '-i', input, '-vf', `${select},${pts},${fit}`, ...enc], even ? 'encode even loop' : 'encode loop')
}

// ── read the result back, at its own loop point ─────────────────────────────
const out = probe(OUT)
const oFirst = join(tmp, 'out-first.png')
const oLast = join(tmp, 'out-last.png')
ffmpeg(FF, ['-hide_banner', '-y', '-i', OUT, '-vf', "select='eq(n,0)'", '-frames:v', '1', oFirst], 'output first frame')
ffmpeg(FF, ['-hide_banner', '-y', '-i', OUT, '-vf', `select='eq(n,${out.frames - 1})'`, '-frames:v', '1', oLast], 'output last frame')
const outStep = step(oLast, oFirst)
const outDiffs = motionDiffs(OUT)
const outMotion = motionProfile(outDiffs)
const outSeam = seamVerdict(outStep, outMotion.median)
ffmpeg(FF, ['-hide_banner', '-y', '-i', oLast, '-i', oFirst, '-filter_complex', '[0]scale=960:-2[a];[1]scale=960:-2[b];[a][b]hstack', '-q:v', '3', SHEET], 'seam sheet')
if (PREVIEW) ffmpeg(FF, ['-hide_banner', '-y', '-stream_loop', String(cycles - 1), '-i', OUT, '-c', 'copy', '-movflags', '+faststart', PREVIEW], 'preview')

const bytes = readFileSync(OUT)
let sidecar = null
const sc = input.replace(/\.master\.mp4$|\.mp4$/i, '.footage.json')
if (existsSync(sc))
  try {
    const j = JSON.parse(readFileSync(sc, 'utf8'))
    sidecar = { provider: j.provider ?? null, model: j.model ?? null, requestId: j.requestId ?? null, costUsdEstimated: j.costUsdEstimated ?? null, renderedAt: j.renderedAt ?? null, refs: (j.refs ?? []).map((r) => ({ kind: r.kind, file: r.file ?? r.ref, sha1: r.sha1 })) }
  } catch {
    sidecar = null
  }
const report = {
  source: rel(input),
  sidecar,
  probe: src,
  motion: { medianStep: r2(motion.median), easeIn: r2(motion.easeIn), easeOut: r2(motion.easeOut) },
  tail,
  cut,
  seam: { step: seamStep, medianStep: r2(motion.median), ratio: seam.ratio == null ? null : r2(seam.ratio), seamless: seam.seamless },
  even: even ? { kept: even.kept, dropped: even.dropped, targetStep: even.targetStep } : null,
  pingpong: PINGPONG,
  blend,
  output: { file: rel(OUT), ...out, size: `${out.width}x${out.height}`, bytes: bytes.length, sha1: createHash('sha1').update(bytes).digest('hex') },
  outputMotion: { medianStep: r2(outMotion.median), easeIn: r2(outMotion.easeIn), easeOut: r2(outMotion.easeOut) },
  outputSeam: { step: outStep, medianStep: r2(outMotion.median), ratio: r2(outSeam.ratio), seamless: outSeam.seamless },
  preview: PREVIEW ? rel(PREVIEW) : null,
  seamSheet: rel(SHEET),
  at: new Date().toISOString(),
}
writeFileSync(REPORT, JSON.stringify(report, null, 2) + '\n')

const dest = arg('out')
if (dest) {
  mkdirSync(dirname(resolve(dest)), { recursive: true })
  copyFileSync(OUT, resolve(dest))
  if (PREVIEW) copyFileSync(PREVIEW, resolve(dest).replace(/(\.[a-z0-9]+)$/i, `-x${cycles}$1`))
}
rmSync(tmp, { recursive: true, force: true })

console.log(`\n  done · ${out.frames} frames · ${out.seconds}s · ${out.width}x${out.height} · ${(bytes.length / 1048576).toFixed(1)} MB · ${rel(OUT)}`)
console.log(`  loop point in the file: steps ${outStep?.toFixed(2)} = ×${outSeam.ratio.toFixed(2)} of its normal step → ${outSeam.seamless ? 'seamless' : 'still a visible step (try --blend N)'} · pace in ×${outMotion.easeIn.toFixed(2)} out ×${outMotion.easeOut.toFixed(2)}`)
console.log(`  report ${rel(REPORT)} · seam sheet ${rel(SHEET)}${PREVIEW ? ` · preview ${rel(PREVIEW)}` : ''}${dest ? ` · copied to ${dest}` : ''}\n`)
process.exit(outSeam.seamless ? 0 : 2)
