/**
 * THE LOOP MATH — how a generated shot becomes a seamless loop. Pure: nothing
 * here runs ffmpeg, reads a file or spends.
 *
 * A loop is generated by handing the model the SAME image as first and last
 * frame (`refs.images: [still, still]`), so the clip arrives back where it
 * began. Two things still stand between that clip and a clean loop:
 *
 *   1. THE DUPLICATE. The last frame repeats the first, so playing the file on
 *      `loop` shows that moment twice: a one-frame hitch every cycle. Models
 *      also land on the end frame a few frames early or late, so the duplicate
 *      is searched for in the tail (best SSIM against frame 0) and everything
 *      from it onward is dropped.
 *   2. THE BRAKE. To hit the end frame some models slow into it and start out
 *      of it slowly, which reads as the scene breathing once per cycle. The
 *      motion profile (mean luma change between successive frames) says by how
 *      much; a seam that steps further than its neighbours do is blended: the
 *      head of the clip is cross-faded over its tail, and the loop point moves
 *      into that blend where no step exists.
 */

/** The median of a list of numbers; 0 for an empty list. */
export function median(xs) {
  const a = xs.filter((x) => Number.isFinite(x)).sort((p, q) => p - q)
  if (!a.length) return 0
  const m = a.length >> 1
  return a.length % 2 ? a[m] : (a[m - 1] + a[m]) / 2
}

const mean = (xs) => (xs.length ? xs.reduce((n, x) => n + x, 0) / xs.length : 0)

/**
 * The motion profile's verdicts. `diffs[i]` is the mean absolute luma change
 * from frame i-1 to frame i (frame 0 has none). Returns the median step over the
 * middle of the clip and, for each edge (`edge` of the clip), how the steps there
 * compare with that median: `easeIn`/`easeOut` of 1 is even motion, 0.4 is a
 * clip that brakes to a quarter of its pace into the end frame.
 */
export function motionProfile(diffs, edge = 0.1) {
  const d = diffs.filter((x) => Number.isFinite(x))
  if (d.length < 4) return { median: median(d), easeIn: 1, easeOut: 1, frames: d.length }
  const k = Math.max(1, Math.round(d.length * edge))
  const mid = d.slice(k, d.length - k)
  const med = median(mid.length ? mid : d) || 1e-9
  return { median: med, easeIn: mean(d.slice(0, k)) / med, easeOut: mean(d.slice(-k)) / med, frames: d.length }
}

/**
 * Where to cut. `tail` lists the candidate duplicate frames as
 * `{ index, ssim }` (ssim against frame 0). The best match is the duplicate when
 * it clears `dupSsim`; the loop then keeps frames [0, index) and drops the rest.
 * A tail that never matches keeps every frame — the loop point is then the
 * clip's own last → first step, and the seam verdict decides whether it blends.
 */
export function pickCut(frames, tail, { dupSsim = 0.97 } = {}) {
  let best = null
  for (const t of tail ?? []) if (Number.isFinite(t?.ssim) && Number.isInteger(t?.index) && t.index > 0 && t.index < frames && (!best || t.ssim > best.ssim)) best = t
  if (best && best.ssim >= dupSsim) return { cut: best.index, dropped: frames - best.index, duplicate: best.index, ssim: best.ssim }
  return { cut: frames, dropped: 0, duplicate: null, ssim: best?.ssim ?? null }
}

/**
 * Whether a plain cut is seamless: the step from the loop's last frame back to
 * its first, as a multiple of the median step between neighbouring frames. A
 * ratio at or under `ratio` is a step the eye already accepts everywhere else in
 * the clip.
 */
export function seamVerdict(seamStep, medianStep, { ratio = 1.6 } = {}) {
  const r = medianStep > 0 ? seamStep / medianStep : seamStep > 0 ? Infinity : 0
  return { seamless: r <= ratio, ratio: r }
}

/**
 * The recipe for a blended seam over `n` frames of a `cut`-frame loop at `fps`:
 * body = frames [n, cut), head = frames [0, n); the head fades in over the body's
 * last n frames (ffmpeg xfade: duration, offset). The result has cut - n frames
 * and its loop point, last frame n-1 → first frame n, is one ordinary step.
 * Refuses a blend the clip is too short to carry (needs cut > 3n).
 */
export function blendPlan(cut, n, fps) {
  if (!(Number.isInteger(cut) && Number.isInteger(n) && n > 0 && fps > 0)) throw new Error('blendPlan: cut and n must be integers, fps positive')
  if (cut <= 3 * n) throw new Error(`blendPlan: ${cut} frames cannot carry a ${n}-frame blend (needs more than ${3 * n})`)
  return { n, bodyFrom: n, bodyTo: cut, headTo: n, durationSec: n / fps, offsetSec: (cut - 2 * n) / fps, outFrames: cut - n }
}

/** Frames for a blend of about `sec` seconds at `fps`, never fewer than 2. */
export const blendFrames = (fps, sec = 0.33) => Math.max(2, Math.round(fps * sec))

/**
 * Even out the pace. `steps[j]` is the motion from frame j to frame j+1 over the
 * kept frames [0, cut); `seamStep` the motion from the last kept frame back to
 * frame 0. Output frames are re-picked at equal increments of cumulative motion
 * (`targetStep` each, the clip's median by default), so a stretch where the
 * model braked into its end frame plays through at the clip's own pace instead
 * of parking. Frames are only ever dropped, never duplicated or invented; the
 * result starts at frame 0 and is strictly increasing. An even clip comes back
 * whole.
 */
export function evenFrames(steps, cut, seamStep, targetStep) {
  const all = Array.from({ length: Math.max(0, cut | 0) }, (_, i) => i)
  if (!(cut > 1) || !(targetStep > 0)) return all
  const S = [0]
  for (let i = 1; i < cut; i++) S.push(S[i - 1] + (Number.isFinite(steps[i - 1]) ? Math.max(0, steps[i - 1]) : targetStep))
  const total = S[cut - 1] + Math.max(0, Number.isFinite(seamStep) ? seamStep : targetStep)
  const K = Math.max(1, Math.round(total / targetStep))
  const out = [0]
  let i = 0
  for (let j = 1; j < K; j++) {
    const target = (j * total) / K
    while (i + 1 < cut && Math.abs(S[i + 1] - target) <= Math.abs(S[i] - target)) i++
    if (i > out[out.length - 1]) out.push(i)
  }
  return out
}
